### ISSUE TITLE
Automagic PDF

### ISSUE THREAD

**Issue by drphilmarshall** [danielgruen/sumzz#4]
I learned how to do this at AHW2016, where Dan FM made the following Travis file:

https://github.com/davidwhogg/mcmc/blob/master/.travis.yml

**Comment by cpadavis** [comment]
oh cool.

I am trying just blatantly copying everything there, even though we currently don't need about 90% of it (since we have no python code in the repo).

It looks like we need Daniel to set up travis-ci on his repo. (Don't worry -- it's really easy!) I've made a temporary fork for now to show what it looks like: https://github.com/cpadavis/sumzz . Or it will be in a couple hours once travis finds it :(

**Comment by drphilmarshall** [comment]
Good idea to get it set up in your fork first!

**Comment by cpadavis** [comment]
OK one undocumented thing: you need to use a github api token and set it in the travis.

[tokens](https://github.com/settings/tokens)
settings: https://travis-ci.org/[username]/sumzz/settings

**Comment by drphilmarshall** [comment]
Hey @cpadavis you should submit a pull request!

**Comment by danielgruen** [comment]
Pull request accepted, travis user name changed, seems to work fine!

**Comment by cpadavis** [comment]
you gotta change the other instances of cpadavis to danielgruen too! I fixed that for you.

**Comment by cpadavis** [comment]
Hi Daniel,

It looks like you need to set up your travis-ci account and activate pushes to sumzz. We can go over this in Philadelphia, but it's pretty easy.

**Comment by danielgruen** [comment]
Ah, well ... I _think_ I turned it on and have it active on pushes. Do I need to set any environment variables in travis-ci (like GITHUB_API_KEY)?

**Comment by cpadavis** [comment]
don't worry -- I set it up for you. It now works (hooray!) though it took a few tries for some reason...

**Comment by drphilmarshall** [comment]
Well done, chaps.

**Comment by drphilmarshall** [comment]
Just seen the [README](https://github.com/danielgruen/sumzz/blob/master/README.md) - nicely done, @cpadavis ! :-)
